name = "Timers"
uuid = "21f18d07-b854-4dab-86f0-c15a3821819a"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
TestEnv = "1e6cf692-eddd-4d53-88a5-2d735e33781b"

[compat]
julia = "1"
TestEnv = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
